name: Deploy to Fargate

on:
  push:
    branches:
      - develop
      - release/*
      - master

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          instance-ids: i-04830bd1976f0fe7b

         # working-directory: /home/ssm-user/ri-backend/prod/ri-backend
          working-directory: /home/ssm-user/sohail/Reposite
         # command: git pull && touch ri_backend/.env1 && aws s3 cp s3://common-webportal-env/ri-backend/prod.env ri_backend/.env1 && cat ri_backend/.env1
          command: ./ssm.sh
          comment: Hello world!

      # Catch SSM outputs
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
