name: Deploy

on:
  push:
    branches:
      - develop
      - 'release/*'
      - master

jobs:
  ec2-status-job:
    name: Checkout & Checking EC2 Status
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Run start_stop.sh
        run: |
          ls && pwd  # Change to your repository's root directory
          chmod +x start_stop.sh
          ./start_stop.sh

  ec2-deploy-job:
    name: Deploy on EC2
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 

      - name: Git Pull and Create Custom File
        run: |
          cd /home/ubuntu/Reposite/
          git checkout master
          touch testec2startandstop
          ls -al
          git pull
