name: Deploy

on:
  push:
    branches:
      - develop
      - release/*
      - master

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2 
      - name: git pull and create custom file
        run: |
          cd Reposite/ 
          touch github.actions-runner
          ls -al
          git clone
          
