name: Deploy to Fargate

on:
  push:
    branches:
      - develop
      - release/*
      - master

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Run aws ssm send-command
        uses: nohmad/aws-ssm-send-command-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          targets: |
             [{"Key":"InstanceIds","Values":["i-04830bd1976f0fe7b"]}]
          document-name: AWS-RunShellScript
          parameters: |
             {"commands":["git pull origin master"]}
